- hosts: webservers
  become: yes
  vars_files:
  - vars.yml
  tasks:



    - name: Update apt-get repo and cache
      become: yes
      apt: update_cache=yes force_apt_get=yes cache_valid_time=3600

    - name: Upgrade all apt packages
      become: yes
      apt: upgrade=dist force_apt_get=yes

    - name: update nodejs package
      ansible.builtin.shell: curl -fsSL https://deb.nodesource.com/setup_15.x | sudo -E bash -

    - name: install nodejs
      apt:
        name: nodejs
        state: present


    - name: create .env file
      copy:
        dest: "/home/{{ USERNAME }}/bootcamp-app/.env"
        content: |
          # Host configuration
          PORT=8080
          HOST={{ HOST }}
          HOST_URL="{{ HOST_URL_VAR }}"
          COOKIE_ENCRYPT_PWD=superAwesomePasswordStringThatIsAtLeast32CharactersLong!
          NODE_ENV=development
          
          
          # POSTGES SQL
          PGHOST={{ PGHOST }}
          PGUSER={{ PGUSER }}
          PGDATABASE={{ PGDATABASE }}
          PGPASSWORD={{ PGPASSWORD }}
          PGPORT=5432
          
          
          
          # Okta configuration
          OKTA_ORG_URL="{{ OKTA_ORG_URL_VAR }}"
          OKTA_CLIENT_ID= {{ OKTA_CLIENT_ID_VAR }}
          OKTA_CLIENT_SECRET="{{ OKTA_CLIENT_SECRET_VAR }}"
          
    - name: install dependencies
      become: yes
      command: "npm install {{ item }}"
      args:
        chdir: /home/{{ USERNAME }}/bootcamp-app
      with_items:
        - '@hapi/hapi@19'
        - '@hapi/bell@12' 
        - '@hapi/boom@9'
        - '@hapi/cookie@11' 
        - '@hapi/inert@6'
        - '@hapi/joi@17' 
        - '@hapi/vision@6' 
        - 'dotenv@8'
        - 'ejs@3' 
        - 'postgres@1'
        
    - name: install nodemon
      become: yes
      command: "npm install --save-dev nodemon@2"
      args:
        chdir: /home/{{ USERNAME }}/bootcamp-app
        
    - name: init db1
      hosts: webserver1
      become: yes
      command: "npm run initdb"
      args:
        chdir: /home/{{ USERNAME }}/bootcamp-app
        
    - name: create myapp.service file
      copy:
        dest: "/etc/systemd/system/myapp.service"
        content: |
          [Unit]
          Description=Nodejs application server
          After=network.target
          [Service]
          WorkingDirectory=/home/iliyab09/bootcamp-app
          ExecStart=/usr/bin/npm run dev
          Type=simple
          Restart=on-failure
          RestartSec=10
          [Install]
          WantedBy=multi-user.target
          
    - name: init db2
      hosts: webserver2
      become: yes
      command: "npm run initdb"
      args:
        chdir: /home/{{ USERNAME }}/bootcamp-app
          
    - name: daemon-reload
      become: yes
      command: "systemctl daemon-reload"
       
    - name: enable myapp
      become: yes
      command: "systemctl enable myapp.service"
       
    - name: start myapp
      become: yes
      command: "systemctl start myapp.service"